master:
  adminUser: "admin"
  adminPassword: "admin"
  image: "jenkins/jenkins"
  tag: "lts"
  imagePullPolicy: "Always"
  installPlugins:
    - kubernetes
    - workflow-job
    - workflow-aggregator
    - credentials-binding
    - git
    - configuration-as-code
    - pipeline-utility-steps
#    - kubernetes:1.28.2
#    - workflow-job:2.40
#    - workflow-aggregator:2.6
#    - credentials-binding:1.24
#    - git:4.4.5
#    - configuration-as-code:1.46
#    - pipeline-utility-steps:2.6.1
  overwritePlugins: true
  ingress:
    enabled: false
    paths:
      - /*
    hostName: jenkins.localhost
    annotations:
      kubernetes.io/ingress.class: istio
agent:
  enabled: true
  image: "jenkins/inbound-agent"
  tag: "4.3-4"
  alwaysPullImage: false
persistence:
  enabled: false
