apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  volumes:
    - name: maven-repository
      hostPath:
        path: /root/.m2/repository
        type: DirectoryOrCreate
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: git
      image: alpine/git:v2.26.2
      command:
        - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: git
    - name: maven
      image: maven:3.6.0-jdk-8-alpine
      command:
        - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: maven
      volumeMounts:
        - name: maven-repository
          mountPath: /root/.m2/repository
    - name: docker
      image: docker:19.03
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: helm
      image: alpine/helm:3.3.4
      command:
        - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: helm