pipeline {

  agent {
    kubernetes {
      yamlFile 'jenkins/KubernetesPod.yaml'
    }
  }

//   environment{
//     IMAGE_TAG =  sh(returnStdout: true,script: 'echo $image_tag').trim()
//     ORIGIN_REPO =  sh(returnStdout: true,script: 'echo $origin_repo').trim()
//     REPO =  sh(returnStdout: true,script: 'echo $repo').trim()
//     BRANCH =  sh(returnStdout: true,script: 'echo $branch').trim()
//   }

  stages {
    stage('Git'){
        steps{
            echo 'echo begin'
//             echo ${IMAGE_TAG}
//             echo ${ORIGIN_REPO}
//             echo ${REPO}
//             echo ${BRANCH}
            echo 'echo end'
            git branch: 'mester', credentialsId: '', url: 'https://github.com/QinhuaZhao/qcc-spring-boot.git'
        }
    }
    stage('Run maven') {
      steps {
        sh 'set'
        sh "echo OUTSIDE_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}"
        container('maven') {
          sh 'echo MAVEN_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}'
          sh 'mvn -version'
          sh 'mvn package -B -DskipTests'
        }
        container('busybox') {
          sh 'echo BUSYBOX_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}'
          sh '/bin/busybox'
        }
      }
    }
  }
}