apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  volumes:
    - name: maven-repository
      hostPath:
        path: /root/.m2/repository
        type: DirectoryOrCreate
    - name: kaniko-cache
      hostPath:
        path: /tmp/kaniko-cache"
        type: DirectoryOrCreate
    - name: docker-cfg
      projected:
        sources:
          - secret:
              name: dockerhub-registry-regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: maven
      image: maven:3.3.9-jdk-8-alpine
      command:
        - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: maven
      volumeMounts:
        - name: maven-repository
          mountPath: /root/.m2/repository
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /busybox/cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: kaniko
      volumeMounts:
        - name: kaniko-cache
          mountPath: /cache
        - name: docker-cfg
          mountPath: /kaniko/.docker
#    - name: kaniko-warmer
#      image: gcr.io/kaniko-project/executor:debug
#      command:
#        - /busybox/cat
#      tty: true
#      env:
#        - name: CONTAINER_ENV_VAR
#          value: kaniko-warmer
#      volumeMounts:
#        - name: kaniko-cache
#          mountPath: /cache
#        - name: docker-cfg
#          mountPath: /kaniko/.docker
#    - name: busybox
#      image: busybox:latest
#      command:
#        - cat
#      tty: true
#      env:
#        - name: CONTAINER_ENV_VAR
#          value: busybox
    - name: kubectl
      image: bitnami/kubectl:1.18.8
      securityContext:
        runAsUser: 1000
      command:
        - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: kubectl
    - name: helm
      image: alpine/helm:3.3.4
      command:
        - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: kubectl